server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cash
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234





